name: dentalk_anatomy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  introduction_screen: ^3.0.2
  shared_preferences: ^2.0.15

flutter: 
  uses-material-design: true
  assets:
    - assets/

